#!/usr/bin/python3
# -*-python-*-

from __future__ import division, print_function

import argparse
import logging

import autolockd

ap = argparse.ArgumentParser()
ap.add_argument('--version', action='version', version=autolockd.__version__)
ap.add_argument('-f', '--config-file', default=None,
                help='Set alternative config file [default ~/.autolockd]')
ap.add_argument('-v', '--verbose', action='count', default=0,
                help='Increase verbosity level')

args = ap.parse_args()

LEVEL_MAP = {
  0: 'ERROR',
  1: 'WARNING',
  2: 'INFO',
  3: 'DEBUG'
}

logging.basicConfig(format='[%(name)s] [%(levelname)s] %(message)s',
                    level=LEVEL_MAP.get(args.verbose, 'DEBUG'))

autolockd.setup_mainloop()
lockd = autolockd.Autolockd(args.config_file)
lockd.run()
